# Feature construction

In [1]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [5]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [6]:
df['Family members']=df['SibSp']+df['Parch']+1

In [7]:
df

      Age  Pclass  SibSp  Parch  Survived  Family members
0    22.0       3      1      0         0               2
1    38.0       1      1      0         1               2
2    26.0       3      0      0         1               1
3    35.0       1      1      0         1               2
4    35.0       3      0      0         0               1
..    ...     ...    ...    ...       ...             ...
886  27.0       2      0      0         0               1
887  19.0       1      0      0         1               1
888   NaN       3      1      2         0               4
889  26.0       1      0      0         1               1
890  32.0       3      0      0         0               1

[891 rows x 6 columns]

In [14]:
def fun(x):
    if x == 1:
        return 0
    elif 1 < x < 4:
        return 1
    else:
        return 2

In [15]:
df['Family_Category'] = df['Family members'].apply(fun)

In [17]:
df.head()

    Age  Pclass  SibSp  Parch  Survived  Family members  Family_Category
0  22.0       3      1      0         0               2                1
1  38.0       1      1      0         1               2                1
2  26.0       3      0      0         1               1                0
3  35.0       1      1      0         1               2                1
4  35.0       3      0      0         0               1                0

In [20]:
df.drop(columns=['SibSp','Parch','Family members'],inplace=True)

In [21]:
df

      Age  Pclass  Survived  Family_Category
0    22.0       3         0                1
1    38.0       1         1                1
2    26.0       3         1                0
3    35.0       1         1                1
4    35.0       3         0                0
..    ...     ...       ...              ...
886  27.0       2         0                0
887  19.0       1         1                0
888   NaN       3         0                2
889  26.0       1         1                0
890  32.0       3         0                0

[891 rows x 4 columns]

# Data spliting

In [22]:
df=pd.read_csv('train.csv')

In [24]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0000,B96 B98,S
833,834,0,3,"Augustsson, Mr. Albert",male,23.0,0,0,347468,7.8542,NaN,S
379,380,0,3,"Gustafsson, Mr. Karl Gideon",male,19.0,0,0,347069,7.7750,NaN,S
500,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S
593,594,0,3,"Bourke, Miss. Mary",female,NaN,0,2,364848,7.7500,NaN,Q

In [26]:
df['title']=df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

In [27]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,title
553,554,1,3,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22.0,0,0,2620,7.225,NaN,C,Mr
589,590,0,3,"Murdlin, Mr. Joseph",male,NaN,0,0,A./5. 3235,8.050,NaN,S,Mr
722,723,0,2,"Gillespie, Mr. William Henry",male,34.0,0,0,12233,13.000,NaN,S,Mr
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.350,NaN,S,Mrs
818,819,0,3,"Holm, Mr. John Fredrik Alexander",male,43.0,0,0,C 7075,6.450,NaN,S,Mr